version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: loganomaly
      POSTGRES_PASSWORD: loganomaly
      POSTGRES_DB: anomalies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loganomaly -d anomalies"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./dashboard/pgadmin/servers.json:/pgadmin4/servers.json:ro

  producer:
    build: .
    depends_on:
      - kafka
    command: python ingestion/kafka_producer.py
    environment:
      KAFKA_BOOTSTRAP: kafka:29092

  detector:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    command: python main.py
    environment:
      KAFKA_BOOTSTRAP: kafka:29092
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: anomalies
      POSTGRES_USER: loganomaly
      POSTGRES_PASSWORD: loganomaly

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboard/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./dashboard/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  pgdata:
  grafana_data:
  pgadmin_data: